### ISSUE TITLE
no images on the post about "Point Pattern Analysis"

### ISSUE THREAD

**Issue by mgacc0** [coreysparks/coreysparks.github.io#1]
I would be interested in reading your article https://coreysparks.github.io/blog/intro-to-point-pattern-analysis-using-r-and-qgis/
But I think that, in one of your later commits to the repo, the images (PNG chunks) got deleted.
So the html remains readable but there are no images.
Do you have some time to revise it?

**Comment by coreysparks** [comment]
Sorry, it's the format for that blog, i've re-done it here and everything works now
[New Link](https://coreysparks.github.io/posts/2021-03-23-point-pattern-analysis-using-r-and-qgis/)

**Comment by mgacc0** [comment]
Thanks!
Interesting article, by the way.

**Comment by coreysparks** [comment]
Glad you found it useful!
